name: Test

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint daemon
        uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018
      - uses: actions/setup-node@v2
        with:
          node-version: '13'
      - name: lint web
        run: |
          make install-dependencies lint-web
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ darwin, linux, windows ]
        arch: [ arm64, amd64 ]
        exclude:
          - os: windows
            arch: arm64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^v1.16
      - name: build ${{ matrix.os }}/${{ matrix.arch }}
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} make build-web static